apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    spec:
      containers:
      - name: grafana
        resources:
        limits:
          memory: 512Mi
        request:
          memory: 256Mi