apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    spec:
      containers:
      - name: grafana
        livenessProbe:
           failureThreshold: 3
           httpGet:
             path: /
             port: 3000
             scheme: HTTP
           periodSeconds: 10
           successThreshold: 1
           timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5