apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
 name: "grafana"
spec:
 storageClassName: manual
 accessModes:
  - "ReadWriteMany"
 resources:
  requests:
   storage: "1Gi"
 volumeName: pv0001
