apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
 name: "grafana"
 finalizers:
  - kubernetes.io/pvc-protection
spec:
 accessModes:
  - "ReadWriteOnce"
 resources:
  requests:
   storage: "1Gi"
 volumeName: pv0001
